FROM ibm-semeru-runtimes:open-17-jdk-focal
ENV LANG=ja_JP.UTF-8
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y procps vim gdb net-tools wget unzip libwebkit2gtk-4.0 firefox xfce4 tightvncserver language-pack-ja fonts-vlgothic
ENV USER=root
RUN printf "passw0rd\npassw0rd\n\n" | vncpasswd
CMD ["bash"]
