apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdpro-deployment
  labels:
    app: pdpro
spec:
  selector:
    matchLabels:
      app: pdpro
  template:
    metadata:
      labels:
        app: pdpro
    spec:
      containers:
      - name: pdpro-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/pdpro:[build-date]
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: docker-user-secret
--- 
apiVersion: v1
kind: Service
metadata:
  name: pdpro-service
spec:
  selector:
    app: pdpro
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Route
metadata:
  name: pdpro-route
spec:
  to:
    kind: Service
    name: pdpro-service
