apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-heapdump-deployment
  labels:
    app: crash-heapdump
spec:
  selector:
    matchLabels:
      app: crash-heapdump
  template:
    metadata:
      labels:
        app: crash-heapdump
    spec:
      containers:
      - name: crash-heapdump-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/crash-heapdump:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: docker-user-secret

--- 
apiVersion: v1
kind: Service
metadata:
  name: crash-heapdump-service
spec:
  selector:
    app: crash-heapdump
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Route
metadata:
  name: crash-heapdump-route
spec:
  to:
    kind: Service
    name: crash-heapdump-service
