apiVersion: apps/v1
kind: Deployment
metadata:
  name: [tag-name]-deployment
  labels:
    app: [tag-name]
spec:
  selector:
    matchLabels:
      app: [tag-name]
  template:
    metadata:
      labels:
        app: [tag-name]
    spec:
      containers:
      - name: [tag-name]-container
        image: image-registry.openshift-image-registry.svc:5000/[project-name]/[tag-name]:[build-name]
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: docker-user-secret

--- 
apiVersion: v1
kind: Service
metadata:
  name: [tag-name]-service
spec:
  selector:
    app: [tag-name]
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: v1
kind: Route
metadata:
  name: [tag-name]-route
spec:
  to:
    kind: Service
    name: [tag-name]-service
